# Specify the version of the Docker Compose file format
version: '3.8'

# Define the services (containers) we want to run
services:
  # Name our service 'db'
  db:
    # Use the official PostgreSQL image, version 14-alpine
    image: postgres:14-alpine
    # Always restart the container if it stops
    restart: always
    # Set environment variables for the database
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1104
      - POSTGRES_DB=ideasiot
    # Map port 5432 on the host machine to port 5432 in the container
    ports:
      - '5432:5432'
    # Persist the database data on the host machine using a volume
    volumes:
      - postgres_data:/var/lib/postgresql/data/

# Define the volume to be managed by Docker
volumes:
  postgres_data: